services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      APP_MONGO_DB: rabobank
      APP_MONGO_USER: test
      APP_MONGO_PASSWORD: test
    restart: always

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
volumes:
  mongo_data: